services:
  go_db:
    container_name: go_db 
    image: postgres:latest 
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: root93@
      POSTGRES_DB: go-api
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgres/data 



volumes:
  pgdata: {}
