services:
  go-app:
    container_name: go-app 
    image: go-api 
    build: . 
    ports:
      - 8080:8080
    depends_on: 
      - go_db
  go_db:
    container_name: go_db 
    image: postgres:latest 
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: root93@
      POSTGRES_DB: go-api
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgres/data 



volumes:
  pgdata: {}
